server:
  port: 8080 # Web后台端口 (给成员A)

spring:
  application:
    name: trading-system
  datasource:
    # 修改为你本地的 MySQL 密码！
    url: jdbc:mysql://localhost:3306/trading_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678    # <--- 请修改这里！！！
    driver-class-name: com.mysql.cj.jdbc.Driver

# 自定义配置
trading:
  gateway:
    tcp-port: 8899        # TCP交易端口 (给成员B)
  exchange:
    sim-delay: 100        # 模拟交易所延迟(ms)

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志
